site_name: pytest-bg-process
site_description: A pytest plugin to start a background process before all tests and kill it on finish.
site_author: IndlgO

theme: readthedocs

repo_url: https://github.com/IndlgO/pytest-bg-process

pages:
  - Home: index.md
